### ISSUE TITLE
cgo error

### ISSUE THREAD

**Issue by runsys** [imtiyazs/webrtc-remote-desktop#4]
**Describe the bug**
sktop # go run -tags "h264enc" cmd/agent.go
# github.com/robotn/gohook
In file included from ../../robotn/gohook/hook.go:22:
In file included from ./event/goEvent.h:18:
In file included from ./event/pub.h:20:
./event/../hook/x11/input_c.h:19:10: fatal error: 'X11/keysym.h' file not found
   19 | #include <X11/keysym.h>
      |          ^~~~~~~~~~~~~~
1 error generated.
# github.com/gen2brain/x264-go/x264c
In file included from ../../gen2brain/x264-go/x264c/common_bitstream.go:7:
In file included from ../../gen2brain/x264-go/x264c/external/x264/common/bitstream.c:27:
In file included from ../../gen2brain/x264-go/x264c/external/x264/common/common.h:811:
../../gen2brain/x264-go/x264c/external/x264/common/rectangle.h:84:9: error: use of undeclared identifier 'v4si'
../../gen2brain/x264-go/x264c/external/x264/common/rectangle.h:86:28: error: use of undeclared identifier '__m128'
../../gen2brain/x264-go/x264c/external/x264/common/rectangle.h:87:28: error: use of undeclared identifier '__m128'
../../gen2brain/x264-go/x264c/external/x264/common/rectangle.h:89:28: error: use of undeclared identifier '__m128'
../../gen2brain/x264-go/x264c/external/x264/common/rectangle.h:90:28: error: use of undeclared identifier '__m128'
# github.com/pion/webrtc/v2
../../pion/webrtc/v2/icecandidate.go:146:3: unknown field Address in struct literal of type sdp.ICECandidate
../../pion/webrtc/v2/icecandidate.go:168:21: c.Address undefined (type sdp.ICECandidate has no field or method Address)
../../pion/webrtc/v2/icecandidate.go:183:67: iceCandidateToSDP(c).Marshal undefined (type sdp.ICECandidate has no field or method Marshal)
../../pion/webrtc/v2/icegatherer.go:88:3: unknown field Trickle in struct literal of type ice.AgentConfig
../../pion/webrtc/v2/icegatherer.go:93:3: unknown field ConnectionTimeout in struct literal of type ice.AgentConfig
../../pion/webrtc/v2/icegatherer.go:97:3: unknown field CandidateSelectionTimeout in struct literal of type ice.AgentConfig
../../pion/webrtc/v2/icegatherer.go:197:15: assignment mismatch: 2 variables but g.agent.GetLocalUserCredentials returns 3 values
../../pion/webrtc/v2/mediaengine.go:71:26: cannot use []byte(sd.SDP) (value of type []byte) as string value in argument to sdp.Unmarshal
../../pion/webrtc/v2/peerconnection.go:465:19: assignment mismatch: 2 variables but d.Marshal returns 1 value
../../pion/webrtc/v2/peerconnection.go:589:19: assignment mismatch: 2 variables but d.Marshal returns 1 value
../../pion/webrtc/v2/peerconnection.go:589:19: too many errors
root@BPC:/media/Generic_MassStorageClass_000000001539_s1/work/code/go/src/github.com/imtiyazs/webrtc-remote-desktop #

OS freebsd.

**Comment by imtiyazs** [comment]
@runsys This is more related to Pion WebRTC and x264 libraries and not this repo. Please post these issues on their Github repos.
